/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://6xms6jiqpbgk7cod4iadcvtaia.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-eekyrvtwsjgdxjzgckza6bs75m",
    "aws_cognito_identity_pool_id": "us-east-2:0e25b432-e4f5-414d-a089-ac31cb2dc874",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_MCDtBhClv",
    "aws_user_pools_web_client_id": "5891caibgh5rin2cgvhlomkrur",
    "oauth": {}
};


export default awsmobile;
